"""Shared authored catalog sources and encoding oracles for locale consumers."""
import struct

HEADER = ('Content-Type: text/plain; charset=UTF-8\n'
          'Plural-Forms: nplurals=4; plural=n==1?0:n==2?1:n==0?2:3;\n')
MESSAGES = {'': HEADER, 'hello': 'bonjour', 'cafe': 'café',
            'one\0many': 'un\0deux\0aucun\0plusieurs',
            'line\n': 'ligne\n', 'joined': 'assemblé'}
PO = ('''# translator comment
#. generated comment
#: source.c:1
msgid ""
msgstr ""
"Content-Type: text/plain; charset=UTF-8\\n"
"Plural-Forms: nplurals=4; plural=n==1?0:n==2?1:n==0?2:3;\\n"

msgid "hello"
msgstr "bonjour"
msgid "cafe"
msgstr "café"
msgid "one"
msgid_plural "many"
msgstr[0] "un"
msgstr[1] "deux"
msgstr[2] "aucun"
msgstr[3] "plusieurs"
msgid "line\\n"
msgstr "ligne\\n"
msgid "join"
"ed"
msgstr "assem"
"blé"
#, fuzzy
msgid "draft"
msgstr "brouillon"
''').encode()


def mo_bytes(messages):
    """Hand-assemble GNU revision-0 catalogs; this never invokes msgfmt."""
    pairs = sorted((key.encode(), value.encode()) for key, value in messages.items())
    count = len(pairs)
    offset = 28 + count * 16
    originals, translations, data = [], [], bytearray()
    for key, _ in pairs:
        originals.append((len(key), offset + len(data)))
        data.extend(key + b'\0')
    for _, value in pairs:
        translations.append((len(value), offset + len(data)))
        data.extend(value + b'\0')
    header = struct.pack('<7I', 0x950412de, 0, count, 28, 28 + count * 8, 0, 0)
    return header + b''.join(struct.pack('<2I', *entry) for entry in originals + translations) + data


# Expected bytes are literal, not generated by the utility under qualification.
ENCODINGS = {
    'UTF-8': b'caf\xc3\xa9\n',
    'ISO-8859-1': b'caf\xe9\n',
    'GB18030': b'\xd6\xd0\xce\xc4\n',
}
GB18030_UTF8 = b'\xe4\xb8\xad\xe6\x96\x87\n'
GERMAN = {'': HEADER, 'hello': 'hallo'}


def load_fixtures(manifest):
    """Read a successful generation, verifying all inputs before returning it.

    Consumers merge profiles[name]['env'] into their subprocess environment.
    Keep this returned record for the run; do not repeatedly read latest state.
    """
    import hashlib
    import json
    from pathlib import Path
    record = json.loads(Path(manifest).read_text())
    if record.get('schema_version') != 1 or not record.get('verified') or record.get('failures'):
        raise ValueError('shared fixture provisioning did not succeed')
    root = Path(record['root'])
    for name, expected in record['files'].items():
        path = root / name
        if not path.resolve().is_relative_to(root.resolve()):
            raise ValueError('fixture file outside generation: ' + name)
        if hashlib.sha256(path.read_bytes()).hexdigest() != expected:
            raise ValueError('fixture hash mismatch: ' + name)
    locales = record['locale_setup']
    for name, expected in locales.get('generated_sha256', {}).items():
        path = Path(locales['locale_path']) / name
        if hashlib.sha256(path.read_bytes()).hexdigest() != expected:
            raise ValueError('locale hash mismatch: ' + name)
    return record
